import { useEffect, useState } from 'react';
import { Trash2, Plus } from 'lucide-react';
import api, { errMsg } from '../api';
import { useToast } from '../context/Toast';
import { useApi, label } from '../utils';
import CrudManager from '../components/CrudManager';
import { PageHead, Tabs, Card, Field, Badge, Spinner } from '../components/ui';

const ACTIONS = [['notify_assignee', 'Notify assignee'], ['notify_manager', 'Notify managers'], ['notify_admin', 'Notify admins'], ['reassign', 'Reassign to least-loaded technician'], ['raise_priority', 'Raise priority']];
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];

function RulesEditor({ value = [], onChange }) {
  const upd = (i, k, v) => onChange(value.map((r, j) => (j === i ? { ...r, [k]: v } : r)));
  return (<div className="col" style={{ gap: 8 }}>{value.map((r, i) => <div key={i} className="row"><span className="small muted">At</span><input className="input" type="number" min="1" max="300" style={{ width: 80 }} value={r.thresholdPct} onChange={(e) => upd(i, 'thresholdPct', +e.target.value)} /><span className="small muted">% of time</span>
    <select className="select" value={r.action} onChange={(e) => upd(i, 'action', e.target.value)}>{ACTIONS.map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><button type="button" className="btn ghost icon" aria-label="Remove rule" onClick={() => onChange(value.filter((_, j) => j !== i))}><Trash2 size={15} /></button></div>)}
    <button type="button" className="btn sm" style={{ alignSelf: 'flex-start' }} onClick={() => onChange([...value, { thresholdPct: 80, action: 'notify_manager' }])}><Plus size={14} />Add rule</button></div>);
}

function OrgSettings() {
  const toast = useToast(); const { data, loading } = useApi(async () => (await api.get('/organizations/current')).data, []); const [f, setF] = useState(null); const [busy, setBusy] = useState(false);
  useEffect(() => { if (data) setF({ name: data.name, domain: data.domain || '', tzOffsetMinutes: data.tzOffsetMinutes, autoCloseDays: data.autoCloseDays, holidays: (data.holidays || []).join(', '), businessHours: { ...data.businessHours } }); }, [data]);
  if (loading || !f) return <Spinner />;
  const bh = (k, v) => setF({ ...f, businessHours: { ...f.businessHours, [k]: v } });
  const toggleDay = (d) => bh('days', f.businessHours.days.includes(d) ? f.businessHours.days.filter((x) => x !== d) : [...f.businessHours.days, d].sort());
  const save = async () => { setBusy(true); try { await api.put('/organizations/current', { ...f, tzOffsetMinutes: +f.tzOffsetMinutes, autoCloseDays: +f.autoCloseDays, holidays: f.holidays.split(',').map((s) => s.trim()).filter(Boolean) }); toast.success('Organisation settings saved'); } catch (e) { toast.error(errMsg(e)); } finally { setBusy(false); } };
  return (<Card title="Organisation and business hours" actions={<button className="btn primary sm" disabled={busy} onClick={save}>Save changes</button>}><div className="grid g2">
    <Field label="Organisation name"><input className="input" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} /></Field><Field label="Email domain"><input className="input" value={f.domain} onChange={(e) => setF({ ...f, domain: e.target.value })} /></Field>
    <Field label="Time zone offset (minutes from UTC)" hint="India is 330. New York is -300 (-240 in summer)."><input className="input" type="number" value={f.tzOffsetMinutes} onChange={(e) => setF({ ...f, tzOffsetMinutes: e.target.value })} /></Field>
    <Field label="Auto-close resolved tickets after (days)" hint="0 turns this off"><input className="input" type="number" min="0" value={f.autoCloseDays} onChange={(e) => setF({ ...f, autoCloseDays: e.target.value })} /></Field>
    <div><Field label="Business hours"><label className="check"><input type="checkbox" checked={f.businessHours.enabled} onChange={(e) => bh('enabled', e.target.checked)} />Use business hours for SLA policies that opt in</label></Field>
      <div className="row"><input className="input" type="time" style={{ width: 130 }} value={f.businessHours.start} onChange={(e) => bh('start', e.target.value)} /><span className="muted">to</span><input className="input" type="time" style={{ width: 130 }} value={f.businessHours.end} onChange={(e) => bh('end', e.target.value)} /></div>
      <div className="chips mt" style={{ marginTop: 10 }}>{DAYS.map((d, i) => <button type="button" key={d} className={`chip ${f.businessHours.days.includes(i) ? 'on' : ''}`} aria-pressed={f.businessHours.days.includes(i)} onClick={() => toggleDay(i)}>{d}</button>)}</div></div>
    <Field label="Holidays" hint="Dates (YYYY-MM-DD) separated by commas. SLA clocks pause on these days."><textarea className="textarea" value={f.holidays} onChange={(e) => setF({ ...f, holidays: e.target.value })} placeholder="2026-10-02, 2026-11-08" /></Field></div></Card>);
}

export default function Settings() {
  const [tab, setTab] = useState('org');
  return (<><PageHead title="Configuration" sub="Organisation, departments, categories, priorities and SLA policies." />
    <Tabs value={tab} onChange={setTab} tabs={[['org', 'Organisation'], ['departments', 'Departments'], ['categories', 'Categories'], ['priorities', 'Priorities'], ['sla', 'SLA policies'], ['orgs', 'All organisations']]} />
    {tab === 'org' && <OrgSettings />}
    {tab === 'departments' && <CrudManager title="Departments" singular="department" endpoint="/departments" columns={[{ key: 'name', label: 'Name', render: (d) => <b>{d.name}</b> }, { key: 'code', label: 'Code' }, { key: 'head', label: 'Head', render: (d) => d.head?.name || '-' }, { key: 'description', label: 'Description' }]} fields={[{ name: 'name', label: 'Name' }, { name: 'code', label: 'Short code' }, { name: 'description', label: 'Description', type: 'textarea' }]} />}
    {tab === 'categories' && <CrudManager title="Categories" singular="category" endpoint="/categories" description="Keywords help the AI (and the offline fallback) classify tickets. Approval-required categories hold work until a manager approves." columns={[{ key: 'name', label: 'Category', render: (c) => <b>{c.name}</b> }, { key: 'keywords', label: 'Keywords', render: (c) => <span className="small muted">{(c.keywords || []).slice(0, 6).join(', ')}</span> }, { key: 'requiresApproval', label: 'Approval', render: (c) => (c.requiresApproval ? <Badge tone="amber">Required</Badge> : '-') }, { key: 'active', label: 'Status', render: (c) => <Badge tone={c.active ? 'green' : 'gray'}>{c.active ? 'Active' : 'Inactive'}</Badge> }]} fields={[{ name: 'name', label: 'Name' }, { name: 'description', label: 'Description', type: 'textarea' }, { name: 'keywords', label: 'Keywords', type: 'tags', hint: 'Comma separated' }, { name: 'requiresApproval', label: 'Approval', type: 'checkbox', checkLabel: 'Requests need IT manager approval', default: false }, { name: 'active', label: 'Status', type: 'checkbox', checkLabel: 'Active' }]} />}
    {tab === 'priorities' && <CrudManager title="Priorities" singular="priority" endpoint="/priorities" description="Level 1 is the most urgent. The AI uses the descriptions to choose a priority." columns={[{ key: 'level', label: 'Level' }, { key: 'name', label: 'Name', render: (p) => <span className="row gap-sm"><i className="dot" style={{ background: p.color }} /><b>{p.name}</b></span> }, { key: 'description', label: 'Meaning' }]} fields={[{ name: 'name', label: 'Name' }, { name: 'level', label: 'Level (1 = most urgent)', type: 'number' }, { name: 'color', label: 'Colour', type: 'color', default: '#f59f00' }, { name: 'description', label: 'When to use it', type: 'textarea' }]} />}
    {tab === 'sla' && <CrudManager title="SLA policies" singular="SLA policy" endpoint="/sla-policies" description="One policy per priority. Escalation rules fire when the given share of the resolution time has been used." columns={[{ key: 'name', label: 'Policy', render: (s) => <b>{s.name}</b> }, { key: 'priority', label: 'Priority', render: (s) => s.priority?.name }, { key: 'responseMinutes', label: 'First response', render: (s) => `${s.responseMinutes} min` }, { key: 'resolutionMinutes', label: 'Resolution', render: (s) => `${(s.resolutionMinutes / 60).toFixed(1)} h` }, { key: 'useBusinessHours', label: 'Clock', render: (s) => <Badge tone={s.useBusinessHours ? 'blue' : 'violet'}>{s.useBusinessHours ? 'Business hours' : '24x7'}</Badge> }, { key: 'escalationRules', label: 'Escalations', render: (s) => (s.escalationRules || []).length }]}
      fields={[{ name: 'name', label: 'Policy name' }, { name: 'priority', label: 'Priority', type: 'select', source: 'priorities', required: true }, { name: 'responseMinutes', label: 'First response target (minutes)', type: 'number' }, { name: 'resolutionMinutes', label: 'Resolution target (minutes)', type: 'number' }, { name: 'useBusinessHours', label: 'Clock', type: 'checkbox', checkLabel: 'Count business hours only', default: true }, { name: 'escalationRules', label: 'Escalation rules', type: 'custom', default: [], render: ({ value, onChange }) => <RulesEditor value={value || []} onChange={onChange} /> }, { name: 'active', label: 'Status', type: 'checkbox', checkLabel: 'Active' }]} />}
    {tab === 'orgs' && <CrudManager title="Organisations" singular="organisation" endpoint="/organizations" searchable={false} canDelete={false} description="Create organisations and give each an administrator."
      columns={[{ key: 'name', label: 'Name', render: (o) => <b>{o.name}</b> }, { key: 'code', label: 'Code', render: (o) => <span className="mono">{o.code}</span> }, { key: 'domain', label: 'Domain' }, { key: 'active', label: 'Status', render: (o) => <Badge tone={o.active ? 'green' : 'gray'}>{o.active ? 'Active' : 'Inactive'}</Badge> }]}
      fields={[{ name: 'name', label: 'Name' }, { name: 'code', label: 'Code (used for self-registration)', createOnly: true }, { name: 'domain', label: 'Email domain' }, { name: 'tzOffsetMinutes', label: 'Time zone offset (minutes)', type: 'number', default: 0 }, { name: 'active', label: 'Status', type: 'checkbox', checkLabel: 'Active' }, { name: 'adminName', label: 'First admin name', createOnly: true }, { name: 'adminEmail', label: 'First admin email', type: 'email', createOnly: true }, { name: 'adminPassword', label: 'First admin password', type: 'password', createOnly: true }]} />}
  </>);
}
