const express = require('express'), helmet = require('helmet'), cors = require('cors'), morgan = require('morgan');
const config = require('./config');
const sanitize = require('./middleware/sanitize'), audit = require('./middleware/audit'), errorHandler = require('./middleware/error');
const app = express();
app.set('trust proxy', 1);
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: config.clientUrl.split(','), credentials: true }));
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(sanitize);
if (config.env !== 'test') app.use(morgan('dev'));
app.use('/api', audit, require('./routes'));
app.use((req, res) => res.status(404).json({ message: 'Route not found' }));
app.use(errorHandler);
module.exports = app;
